version: '3.7'

services:
  # Groomer Note Talk Server
  nestjs-app:
    container_name: nestjs-app
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - network-backend

  # Reverse Proxy Production version container
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    restart: "unless-stopped"
    depends_on:
      - nestjs-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network-backend

# Docker Network
networks:
  network-backend:
    driver: bridge
    name: network-backend
