version: '3.7'

services:
  # Nest.js Server container
  nestjs-app:
    container_name: nestjs-app
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev
    environment:
      - SERVER_PORT=3000
      - NODE_ENV=development
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - db-postgres
    networks:
      - network-backend

  # Reverse Proxy Production version container
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    restart: "unless-stopped"
    depends_on:
      - nestjs-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network-backend

  # Local PostgreSQL database container
  db-postgres:
    container_name: db-postgres
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - network-backend

# Docker Network
networks:
  network-backend:
    driver: bridge
    name: network-backend
